# Generated by Django 5.2.10 on 2026-01-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_employees',
            field=models.PositiveIntegerField(default=0, help_text='Số nhân sự dự kiến cho dự án'),
        ),
    ]
