# Generated by Django 5.2.10 on 2026-01-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_estimated_employees'),
        ('resources', '0002_alter_employee_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Phòng ban phụ trách dự án', related_name='projects', to='resources.department'),
        ),
    ]
