# Generated by Django 5.2.10 on 2026-01-19 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_departments'),
        ('resources', '0002_alter_employee_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignment_status',
            field=models.CharField(choices=[('assigned', 'Đã giao'), ('accepted', 'Đã nhận'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('rejected', 'Từ chối')], default='assigned', help_text='Trạng thái giao/nhận việc', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Phòng ban phụ trách công việc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='resources.department'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='resources.employee'),
        ),
    ]
