# Generated by Django 5.2.10 on 2026-01-22 04:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_budget_for_personnel_if_not_exists(apps, schema_editor):
    """Add budget_for_personnel field only if it doesn't exist."""
    db_table = 'projects_project'
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_NAME = %s AND COLUMN_NAME = 'budget_for_personnel'
        """, [db_table])
        exists = cursor.fetchone()[0] > 0
        
        if not exists:
            cursor.execute(f"ALTER TABLE [{db_table}] ADD [budget_for_personnel] DECIMAL(15,2) NOT NULL DEFAULT 0")


def create_models_if_not_exist(apps, schema_editor):
    """Create PersonnelRecommendation models only if they don't exist."""
    db = schema_editor.connection.alias
    cursor = schema_editor.connection.cursor()
    
    # Check if PersonnelRecommendation table exists
    cursor.execute("""
        SELECT COUNT(*) 
        FROM INFORMATION_SCHEMA.TABLES 
        WHERE TABLE_NAME = 'projects_personnelrecommendation'
    """)
    pr_exists = cursor.fetchone()[0] > 0
    
    if not pr_exists:
        # Create PersonnelRecommendation table
        cursor.execute("""
            CREATE TABLE [projects_personnelrecommendation] (
                [id] BIGINT IDENTITY(1,1) PRIMARY KEY,
                [created_at] DATETIME2 NOT NULL,
                [updated_at] DATETIME2 NOT NULL,
                [optimization_goal] NVARCHAR(20) NOT NULL,
                [total_estimated_cost] DECIMAL(15,2) NOT NULL DEFAULT 0,
                [reasoning] NTEXT NOT NULL,
                [is_applied] BIT NOT NULL DEFAULT 0,
                [applied_at] DATETIME2 NULL,
                [created_by_id] INT NULL,
                [project_id] BIGINT NOT NULL,
                [updated_by_id] INT NULL
            )
        """)
    
    # Check if PersonnelRecommendationDetail table exists
    cursor.execute("""
        SELECT COUNT(*) 
        FROM INFORMATION_SCHEMA.TABLES 
        WHERE TABLE_NAME = 'projects_personnelrecommendationdetail'
    """)
    prd_exists = cursor.fetchone()[0] > 0
    
    if not prd_exists:
        # Create PersonnelRecommendationDetail table
        cursor.execute("""
            CREATE TABLE [projects_personnelrecommendationdetail] (
                [id] BIGINT IDENTITY(1,1) PRIMARY KEY,
                [created_at] DATETIME2 NOT NULL,
                [updated_at] DATETIME2 NOT NULL,
                [allocation_percentage] DECIMAL(5,2) NOT NULL,
                [estimated_hours] DECIMAL(8,2) NOT NULL DEFAULT 0,
                [estimated_cost] DECIMAL(15,2) NOT NULL DEFAULT 0,
                [reasoning] NTEXT NULL,
                [created_by_id] INT NULL,
                [employee_id] BIGINT NOT NULL,
                [recommendation_id] BIGINT NOT NULL,
                [updated_by_id] INT NULL
            )
        """)
        
        # Add foreign keys and constraints
        cursor.execute("""
            ALTER TABLE [projects_personnelrecommendationdetail]
            ADD CONSTRAINT [fk_prd_recommendation] FOREIGN KEY ([recommendation_id]) 
            REFERENCES [projects_personnelrecommendation]([id]) ON DELETE CASCADE
        """)
        
        cursor.execute("""
            ALTER TABLE [projects_personnelrecommendationdetail]
            ADD CONSTRAINT [fk_prd_employee] FOREIGN KEY ([employee_id]) 
            REFERENCES [resources_employee]([id]) ON DELETE CASCADE
        """)
        
        cursor.execute("""
            ALTER TABLE [projects_personnelrecommendationdetail]
            ADD CONSTRAINT [uq_prd_recommendation_employee] UNIQUE ([recommendation_id], [employee_id])
        """)
    
    # Check if required_departments M2M table exists
    cursor.execute("""
        SELECT COUNT(*) 
        FROM INFORMATION_SCHEMA.TABLES 
        WHERE TABLE_NAME = 'projects_project_required_departments'
    """)
    m2m_exists = cursor.fetchone()[0] > 0
    
    if not m2m_exists:
        cursor.execute("""
            CREATE TABLE [projects_project_required_departments] (
                [id] BIGINT IDENTITY(1,1) PRIMARY KEY,
                [project_id] BIGINT NOT NULL,
                [department_id] BIGINT NOT NULL
            )
        """)
        
        cursor.execute("""
            ALTER TABLE [projects_project_required_departments]
            ADD CONSTRAINT [fk_prd_project] FOREIGN KEY ([project_id]) 
            REFERENCES [projects_project]([id]) ON DELETE CASCADE
        """)
        
        cursor.execute("""
            ALTER TABLE [projects_project_required_departments]
            ADD CONSTRAINT [fk_prd_department] FOREIGN KEY ([department_id]) 
            REFERENCES [resources_department]([id]) ON DELETE CASCADE
        """)
        
        cursor.execute("""
            ALTER TABLE [projects_project_required_departments]
            ADD CONSTRAINT [uq_prd_project_department] UNIQUE ([project_id], [department_id])
        """)


def reverse_create_models(apps, schema_editor):
    """Reverse: Drop tables if needed."""
    pass


def reverse_add_budget_for_personnel(apps, schema_editor):
    """Reverse: Remove budget_for_personnel field."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_task_overdue_status'),
        ('resources', '0007_employeehourlyrate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(add_budget_for_personnel_if_not_exists, reverse_add_budget_for_personnel),
        migrations.RunPython(create_models_if_not_exist, reverse_create_models),
        # State-only operations to update Django's model state
        migrations.AddField(
            model_name='project',
            name='required_departments',
            field=models.ManyToManyField(blank=True, help_text='Các phòng ban bắt buộc cần tham gia dự án', related_name='required_projects', to='resources.department'),
        ),
        migrations.CreateModel(
            name='PersonnelRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('optimization_goal', models.CharField(choices=[('performance', 'Tối ưu hiệu suất'), ('cost', 'Tối ưu chi phí'), ('balanced', 'Cân bằng')], default='balanced', help_text='Mục tiêu tối ưu hóa', max_length=20)),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, default=0, help_text='Tổng chi phí ước tính (VNĐ)', max_digits=15)),
                ('reasoning', models.TextField(help_text='Lý do và phân tích đề xuất')),
                ('is_applied', models.BooleanField(default=False, help_text='Đã áp dụng đề xuất này chưa')),
                ('applied_at', models.DateTimeField(blank=True, help_text='Thời điểm áp dụng', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_recommendations', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đề xuất nhân sự',
                'verbose_name_plural': 'Đề xuất nhân sự',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelRecommendationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation_percentage', models.DecimalField(decimal_places=2, help_text='Tỷ lệ phân bổ (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, help_text='Số giờ ước tính', max_digits=8)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, help_text='Chi phí ước tính (VNĐ)', max_digits=15)),
                ('reasoning', models.TextField(blank=True, help_text='Lý do đề xuất nhân sự này')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.employee')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.personnelrecommendation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chi tiết đề xuất nhân sự',
                'verbose_name_plural': 'Chi tiết đề xuất nhân sự',
                'unique_together': {('recommendation', 'employee')},
            },
        ),
        migrations.AddField(
            model_name='personnelrecommendation',
            name='recommended_employees',
            field=models.ManyToManyField(help_text='Danh sách nhân sự được đề xuất', related_name='recommendations', through='projects.PersonnelRecommendationDetail', to='resources.employee'),
        ),
    ]
