# Generated by Django 5.2.10 on 2026-01-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_budget_for_personnel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget_for_personnel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ngân sách dành cho nhân sự (VNĐ)', max_digits=15),
        ),
    ]
