# Generated by Django 5.2.11 on 2026-03-06 16:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_project_manager_task_priority_milestone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress_percent',
            field=models.IntegerField(default=0, help_text='Tiến độ hoàn thành (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase_name', models.CharField(help_text='Tên giai đoạn', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Thứ tự sắp xếp')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giai đoạn dự án',
                'verbose_name_plural': 'Giai đoạn dự án',
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='phase',
            field=models.ForeignKey(blank=True, help_text='Giai đoạn dự án', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.projectphase'),
        ),
    ]
