# Generated by Django 5.2.11 on 2026-04-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_taskprogresslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delay_penalty_enabled',
            field=models.BooleanField(default=True, help_text='Bat/tat tinh nang phat KPI do tre han cho du an'),
        ),
    ]
