# Generated by Django 5.2.11 on 2026-04-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_delay_penalty_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approved_delay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Thoi diem hoan thanh task', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='days_late',
            field=models.IntegerField(default=0, help_text='So ngay tre han'),
        ),
        migrations.AddField(
            model_name='task',
            name='delay_explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='delay_reason_type',
            field=models.CharField(choices=[('self', 'Ca nhan'), ('dependency', 'Phu thuoc'), ('external', 'Ngoai canh'), ('scope_change', 'Doi pham vi')], default='self', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='delay_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
