# Generated by Django 5.2.11 on 2026-04-03 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_task_approved_delay_task_completed_at_task_days_late_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default Delay Rules', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_explanation_after_days', models.PositiveIntegerField(default=5)),
                ('warning_penalty_level_threshold', models.PositiveIntegerField(default=2)),
                ('no_delay_monthly_reward', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('early_completion_reward_min', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('early_completion_reward_max', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('overdeliver_reward', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('penalty_light', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('penalty_medium', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('penalty_heavy', models.DecimalField(decimal_places=2, default=15, max_digits=6)),
                ('penalty_critical', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cau hinh rule tre han',
                'verbose_name_plural': 'Cau hinh rule tre han',
                'ordering': ['-updated_at'],
            },
        ),
    ]
