# Generated by Django 5.2.11 on 2026-04-03 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_delayruleconfig'),
        ('resources', '0010_employee_at_risk_employee_bonus_reduction_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee_skills_snapshot',
            field=models.TextField(blank=True, default='', help_text='Snapshot ky nang nhan su khi nhan task'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_skills',
            field=models.TextField(blank=True, default='', help_text='Ky nang yeu cau de hoan thanh task'),
        ),
        migrations.AddField(
            model_name='task',
            name='workload_snapshot',
            field=models.PositiveIntegerField(default=0, help_text='So task dang mo cua nhan su tai thoi diem gan/nhan'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('done', 'Done'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='todo', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('status_changed', 'Status Changed')], max_length=30)),
                ('event_note', models.TextField(blank=True, default='')),
                ('task_name_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('task_description_snapshot', models.TextField(blank=True, default='')),
                ('required_skills_snapshot', models.TextField(blank=True, default='')),
                ('employee_skills_snapshot', models.TextField(blank=True, default='')),
                ('started_at_snapshot', models.DateTimeField(blank=True, null=True)),
                ('due_date_snapshot', models.DateField(blank=True, null=True)),
                ('completed_at_snapshot', models.DateTimeField(blank=True, null=True)),
                ('status_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('assignment_status_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('delay_note_snapshot', models.TextField(blank=True, default='')),
                ('workload_at_time', models.PositiveIntegerField(default=0)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_history_entries', to='resources.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='projects.task')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task history',
                'verbose_name_plural': 'Task histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
