# Generated by Django 5.2.11 on 2026-04-03 17:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_task_assignee_skills_snapshot_task_required_skills_and_more'),
        ('resources', '0010_employee_at_risk_employee_bonus_reduction_percent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnelrecommendation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ä\x90á»\x81 xuáº¥t nhÃ¢n sá»±', 'verbose_name_plural': 'Ä\x90á»\x81 xuáº¥t nhÃ¢n sá»±'},
        ),
        migrations.AlterModelOptions(
            name='personnelrecommendationdetail',
            options={'verbose_name': 'Chi tiáº¿t Ä‘á»\x81 xuáº¥t nhÃ¢n sá»±', 'verbose_name_plural': 'Chi tiáº¿t Ä‘á»\x81 xuáº¥t nhÃ¢n sá»±'},
        ),
        migrations.AlterModelOptions(
            name='projectphase',
            options={'ordering': ['order_index', 'created_at'], 'verbose_name': 'Giai Ä‘oáº¡n dá»± Ã¡n', 'verbose_name_plural': 'Giai Ä‘oáº¡n dá»± Ã¡n'},
        ),
        migrations.AlterModelOptions(
            name='taskprogresslog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lá»‹ch sá»\xad cáº\xadp nháº\xadt tiáº¿n Ä‘á»™', 'verbose_name_plural': 'Lá»‹ch sá»\xad cáº\xadp nháº\xadt tiáº¿n Ä‘á»™'},
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Chá»\x9d'), ('in_progress', 'Ä\x90ang thá»±c hiá»‡n'), ('completed', 'HoÃ\xa0n thÃ\xa0nh')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnelrecommendation',
            name='applied_at',
            field=models.DateTimeField(blank=True, help_text='Thá»\x9di Ä‘iá»ƒm Ã¡p dá»¥ng', null=True),
        ),
        migrations.AlterField(
            model_name='personnelrecommendation',
            name='is_applied',
            field=models.BooleanField(default=False, help_text='Ä\x90Ã£ Ã¡p dá»¥ng Ä‘á»\x81 xuáº¥t nÃ\xa0y chÆ°a'),
        ),
        migrations.AlterField(
            model_name='personnelrecommendation',
            name='optimization_goal',
            field=models.CharField(choices=[('performance', 'Tá»‘i Æ°u hiá»‡u suáº¥t'), ('cost', 'Tá»‘i Æ°u chi phÃ\xad'), ('balanced', 'CÃ¢n báº±ng')], default='balanced', help_text='Má»¥c tiÃªu tá»‘i Æ°u hÃ³a', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnelrecommendation',
            name='reasoning',
            field=models.TextField(help_text='LÃ½ do vÃ\xa0 phÃ¢n tÃ\xadch Ä‘á»\x81 xuáº¥t'),
        ),
        migrations.AlterField(
            model_name='personnelrecommendation',
            name='recommended_employees',
            field=models.ManyToManyField(help_text='Danh sÃ¡ch nhÃ¢n sá»± Ä‘Æ°á»£c Ä‘á»\x81 xuáº¥t', related_name='recommendations', through='projects.PersonnelRecommendationDetail', to='resources.employee'),
        ),
        migrations.AlterField(
            model_name='personnelrecommendation',
            name='total_estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tá»•ng chi phÃ\xad Æ°á»›c tÃ\xadnh (VNÄ\x90)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='personnelrecommendationdetail',
            name='allocation_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Tá»· lá»‡ phÃ¢n bá»• (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='personnelrecommendationdetail',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Chi phÃ\xad Æ°á»›c tÃ\xadnh (VNÄ\x90)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='personnelrecommendationdetail',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sá»‘ giá»\x9d Æ°á»›c tÃ\xadnh', max_digits=8),
        ),
        migrations.AlterField(
            model_name='personnelrecommendationdetail',
            name='reasoning',
            field=models.TextField(blank=True, help_text='LÃ½ do Ä‘á»\x81 xuáº¥t nhÃ¢n sá»± nÃ\xa0y'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_for_personnel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='NgÃ¢n sÃ¡ch dÃ\xa0nh cho nhÃ¢n sá»± (VNÄ\x90)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='PhÃ²ng ban phá»¥ trÃ¡ch dá»± Ã¡n', related_name='projects', to='resources.department'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_employees',
            field=models.PositiveIntegerField(default=0, help_text='Sá»‘ nhÃ¢n sá»± dá»± kiáº¿n cho dá»± Ã¡n'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, help_text='Project Manager chÃ\xadnh cá»§a dá»± Ã¡n', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='resources.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='required_departments',
            field=models.ManyToManyField(blank=True, help_text='CÃ¡c phÃ²ng ban báº¯t buá»™c cáº§n tham gia dá»± Ã¡n', related_name='required_projects', to='resources.department'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='order_index',
            field=models.PositiveIntegerField(default=0, help_text='Thá»© tá»± sáº¯p xáº¿p'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='phase_name',
            field=models.CharField(help_text='TÃªn giai Ä‘oáº¡n', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignment_status',
            field=models.CharField(choices=[('assigned', 'Ä\x90Ã£ giao'), ('accepted', 'Ä\x90Ã£ nháº\xadn'), ('in_progress', 'Ä\x90ang thá»±c hiá»‡n'), ('completed', 'HoÃ\xa0n thÃ\xa0nh'), ('rejected', 'Tá»« chá»‘i')], default='assigned', help_text='Tráº¡ng thÃ¡i giao/nháº\xadn viá»‡c', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.ForeignKey(blank=True, help_text='PhÃ²ng ban phá»¥ trÃ¡ch cÃ´ng viá»‡c', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='resources.department'),
        ),
        migrations.AlterField(
            model_name='task',
            name='phase',
            field=models.ForeignKey(blank=True, help_text='Giai Ä‘oáº¡n dá»± Ã¡n', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.projectphase'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Tháº¥p'), ('medium', 'Trung bÃ¬nh'), ('high', 'Cao'), ('critical', 'Kháº©n cáº¥p')], default='medium', help_text='Má»©c Ä‘á»™ Æ°u tiÃªn', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress_percent',
            field=models.IntegerField(default=0, help_text='Tiáº¿n Ä‘á»™ hoÃ\xa0n thÃ\xa0nh (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Thá»\x9di Ä‘iá»ƒm báº¯t Ä‘áº§u tÃ\xadnh giá»\x9d Æ°á»›c tÃ\xadnh', null=True),
        ),
        migrations.AlterField(
            model_name='taskprogresslog',
            name='note',
            field=models.TextField(blank=True, help_text='Ghi chÃº tiáº¿n Ä‘á»™'),
        ),
        migrations.AlterField(
            model_name='taskprogresslog',
            name='progress_percent',
            field=models.IntegerField(help_text='Tiáº¿n Ä‘á»™ táº¡i thá»\x9di Ä‘iá»ƒm cáº\xadp nháº\xadt', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
