# Generated by Django 5.2.11 on 2026-04-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_projectmembershiprequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnelrecommendation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đề xuất nhân sự', 'verbose_name_plural': 'Đề xuất nhân sự'},
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ'), ('in_progress', 'Ä\x90ang thá»±c hiện'), ('completed', 'HoÃ\xa0n thÃ\xa0nh')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_for_personnel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ngân sách dành cho nhân sự (VNĐ)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignment_status',
            field=models.CharField(choices=[('assigned', 'Đã giao'), ('accepted', 'Đã nhận'), ('in_progress', 'Ä\x90ang thá»±c hiện'), ('completed', 'HoÃ\xa0n thÃ\xa0nh'), ('rejected', 'Từ chối')], default='assigned', help_text='Trạng thái giao/nháº\xadn việc', max_length=20),
        ),
    ]
