# Generated by Django 5.2.11 on 2026-04-24 19:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_personnelrecommendationdetail_options_and_more'),
        ('resources', '0011_skill_employeeskill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnelrecommendation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ä\x90á»\x81 xuất nhân sá»±', 'verbose_name_plural': 'Ä\x90á»\x81 xuất nhân sá»±'},
        ),
        migrations.AlterModelOptions(
            name='personnelrecommendationdetail',
            options={'verbose_name': 'Chi tiet de xuat nhan su', 'verbose_name_plural': 'Chi tiet de xuat nhan su'},
        ),
        migrations.AlterModelOptions(
            name='projectphase',
            options={'ordering': ['order_index', 'created_at'], 'verbose_name': 'Giai đoạn dự án', 'verbose_name_plural': 'Giai đoạn dự án'},
        ),
        migrations.AlterModelOptions(
            name='taskprogresslog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lịch sá»\xad cáº\xadp nháº\xadt tiến độ', 'verbose_name_plural': 'Lịch sá»\xad cáº\xadp nháº\xadt tiến độ'},
        ),
        migrations.AddField(
            model_name='task',
            name='planned_start_date',
            field=models.DateField(blank=True, help_text='Ngay bat dau du kien', null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Chá»\x9d'), ('in_progress', 'Ä\x90ang thá»±c hiện'), ('completed', 'HoÃ\xa0n thÃ\xa0nh')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnelrecommendation',
            name='applied_at',
            field=models.DateTimeField(blank=True, help_text='Thá»\x9di Diểm áp dụng', null=True),
        ),
        migrations.AlterField(
            model_name='personnelrecommendation',
            name='is_applied',
            field=models.BooleanField(default=False, help_text='Ä\x90ã áp dụng Dá»\x81 xuất nÃ\xa0y chưa'),
        ),
        migrations.AlterField(
            model_name='personnelrecommendation',
            name='optimization_goal',
            field=models.CharField(choices=[('performance', 'Tối ưu hiệu suất'), ('cost', 'Tối ưu chi phÃ\xad'), ('balanced', 'Cân bằng')], default='balanced', help_text='Mục tiêu tối ưu hóa', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnelrecommendation',
            name='reasoning',
            field=models.TextField(help_text='Lý do vÃ\xa0 phân tÃ\xadch Dá»\x81 xuất'),
        ),
        migrations.AlterField(
            model_name='personnelrecommendation',
            name='recommended_employees',
            field=models.ManyToManyField(help_text='Danh sách nhân sá»± được Dá»\x81 xuất', related_name='recommendations', through='projects.PersonnelRecommendationDetail', to='resources.employee'),
        ),
        migrations.AlterField(
            model_name='personnelrecommendation',
            name='total_estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tổng chi phÃ\xad ước tÃ\xadnh (VNÄ\x90)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='personnelrecommendationdetail',
            name='allocation_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Tỷ lệ phân bổ (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='personnelrecommendationdetail',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Chi phÃ\xad ước tÃ\xadnh (VNÄ\x90)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='personnelrecommendationdetail',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Số giá»\x9d ước tÃ\xadnh', max_digits=8),
        ),
        migrations.AlterField(
            model_name='personnelrecommendationdetail',
            name='reasoning',
            field=models.TextField(blank=True, help_text='Lý do Dá»\x81 xuất nhân sá»± nÃ\xa0y'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_for_personnel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ngân sách dÃ\xa0nh cho nhân sá»± (VNÄ\x90)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Phòng ban phụ trách dự án', related_name='projects', to='resources.department'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_employees',
            field=models.PositiveIntegerField(default=0, help_text='Số nhân sự dự kiến cho dự án'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, help_text='Project Manager chÃ\xadnh cá»§a dá»± án', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='resources.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='required_departments',
            field=models.ManyToManyField(blank=True, help_text='Các phòng ban bắt buộc cần tham gia dự án', related_name='required_projects', to='resources.department'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='order_index',
            field=models.PositiveIntegerField(default=0, help_text='Thứ tự sắp xếp'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='phase_name',
            field=models.CharField(help_text='Tên giai đoạn', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignment_status',
            field=models.CharField(choices=[('assigned', 'Ä\x90ã giao'), ('accepted', 'Ä\x90ã nháº\xadn'), ('in_progress', 'Ä\x90ang thá»±c hiện'), ('completed', 'HoÃ\xa0n thÃ\xa0nh'), ('rejected', 'Từ chối')], default='assigned', help_text='Trang thai giao/nhan viec', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Phòng ban phụ trách công việc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='resources.department'),
        ),
        migrations.AlterField(
            model_name='task',
            name='phase',
            field=models.ForeignKey(blank=True, help_text='Giai đoạn dự án', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.projectphase'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('critical', 'Khẩn cấp')], default='medium', help_text='Mức độ ưu tiên', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress_percent',
            field=models.IntegerField(default=0, help_text='Tiến độ hoÃ\xa0n thÃ\xa0nh (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Thá»\x9di Diểm bắt đầu tÃ\xadnh giá»\x9d ước tÃ\xadnh', null=True),
        ),
        migrations.AlterField(
            model_name='taskprogresslog',
            name='note',
            field=models.TextField(blank=True, help_text='Ghi chú tiến độ'),
        ),
        migrations.AlterField(
            model_name='taskprogresslog',
            name='progress_percent',
            field=models.IntegerField(help_text='Tiến độ tại thá»\x9di Diểm cáº\xadp nháº\xadt', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
