# Generated by Django 5.2.11 on 2026-04-25 08:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_personnelrecommendation_options_and_more'),
        ('resources', '0011_skill_employeeskill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIAdjustmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.DecimalField(decimal_places=2, help_text='So diem dieu chinh, am la tru them, duong la cong bu', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('-20')), django.core.validators.MaxValueValidator(Decimal('20'))])),
                ('reason', models.TextField(help_text='Ly do de xuat dieu chinh KPI')),
                ('review_note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_adjustment_requests', to='resources.employee')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_adjustments_requested', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_adjustments_reviewed', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI adjustment request',
                'verbose_name_plural': 'KPI adjustment requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskDelayScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_delay_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('new_delay_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('delta_delay_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_delay_score_logs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_score_logs', to='resources.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_score_logs', to='projects.task')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task delay score log',
                'verbose_name_plural': 'Task delay score logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
