# Generated by Django 5.2.11 on 2026-04-25 15:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_kpiadjustmentrequest_taskdelayscorelog'),
        ('resources', '0011_skill_employeeskill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnelrecommendation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đề xuất nhân sự', 'verbose_name_plural': 'Đề xuất nhân sự'},
        ),
        migrations.AlterModelOptions(
            name='personnelrecommendationdetail',
            options={'verbose_name': 'Chi tiết đề xuất nhân sự', 'verbose_name_plural': 'Chi tiết đề xuất nhân sự'},
        ),
        migrations.AlterModelOptions(
            name='taskprogresslog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lịch sử cập nhật tiến độ', 'verbose_name_plural': 'Lịch sử cập nhật tiến độ'},
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnelrecommendation',
            name='applied_at',
            field=models.DateTimeField(blank=True, help_text='Thời điểm áp dụng', null=True),
        ),
        migrations.AlterField(
            model_name='personnelrecommendation',
            name='is_applied',
            field=models.BooleanField(default=False, help_text='Đã áp dụng đề xuất này chưa'),
        ),
        migrations.AlterField(
            model_name='personnelrecommendation',
            name='optimization_goal',
            field=models.CharField(choices=[('performance', 'Tối ưu hiệu suất'), ('cost', 'Tối ưu chi phí'), ('balanced', 'Cân bằng')], default='balanced', help_text='Mục tiêu tối ưu hóa', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnelrecommendation',
            name='reasoning',
            field=models.TextField(help_text='Lý do và phân tích đề xuất'),
        ),
        migrations.AlterField(
            model_name='personnelrecommendation',
            name='recommended_employees',
            field=models.ManyToManyField(help_text='Danh sách nhân sự được đề xuất', related_name='recommendations', through='projects.PersonnelRecommendationDetail', to='resources.employee'),
        ),
        migrations.AlterField(
            model_name='personnelrecommendation',
            name='total_estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tổng chi phí ước tính (VNĐ)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='personnelrecommendationdetail',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Chi phí ước tính (VNĐ)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='personnelrecommendationdetail',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Số giờ ước tính', max_digits=8),
        ),
        migrations.AlterField(
            model_name='personnelrecommendationdetail',
            name='reasoning',
            field=models.TextField(blank=True, help_text='Lý do đề xuất nhân sự này'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_for_personnel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ngân sách dành cho nhân sự (VNĐ)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, help_text='Project Manager chính của dự án', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='resources.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignment_status',
            field=models.CharField(choices=[('assigned', 'Đã giao'), ('accepted', 'Đã nhận'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('rejected', 'Từ chối')], default='assigned', help_text='Trang thai giao/nhan viec', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress_percent',
            field=models.IntegerField(default=0, help_text='Tiến độ hoàn thành (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Thời điểm bắt đầu tính giờ ước tính', null=True),
        ),
        migrations.AlterField(
            model_name='taskprogresslog',
            name='progress_percent',
            field=models.IntegerField(help_text='Tiến độ tại thời điểm cập nhật', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
