# Generated by Django 5.2.11 on 2026-04-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_personnelrecommendation_options_and_more'),
        ('resources', '0011_skill_employeeskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, help_text='Danh sach nhan su duoc giao task', related_name='multi_assigned_tasks', to='resources.employee'),
        ),
    ]
