# Generated by Django 5.2.10 on 2026-01-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aichathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('manager', 'Quản lý'), ('employee', 'Nhân viên')], default='employee', help_text='Vai trò của người dùng trong hệ thống.', max_length=20),
        ),
    ]
