# Generated by Django 5.2.10 on 2026-01-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Cá nhân'), ('company', 'Công ty'), ('government', 'Chính phủ')], default='company', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Không hoạt động'), ('prospect', 'Tiềm năng')], default='prospect', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('meeting', 'Cuộc họp'), ('call', 'Cuộc gọi'), ('email', 'Email'), ('proposal', 'Đề xuất'), ('contract', 'Hợp đồng'), ('other', 'Khác')], max_length=20),
        ),
    ]
