# Generated by Django 5.2.10 on 2026-01-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('labor', 'Nhân công'), ('material', 'Vật liệu'), ('equipment', 'Thiết bị'), ('travel', 'Đi lại'), ('other', 'Khác')], max_length=20),
        ),
    ]
