# Generated by Django 5.2.11 on 2026-03-07 10:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0004_budget_approval_status_budget_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategory',
            name='expense_class',
            field=models.CharField(choices=[('COGS', 'Direct Costs (COGS)'), ('OPEX', 'Operating Expenses (OPEX)'), ('TAX', 'Taxes'), ('INTEREST', 'Interest Expense'), ('DEPRECIATION', 'Depreciation & Amortization'), ('CAPEX', 'Capital Expenditures')], default='OPEX', help_text='Phân loại hạng mục chi phí cho báo cáo P&L / EBITDA', max_length=20),
        ),
        migrations.CreateModel(
            name='FinancialForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forecast_type', models.CharField(choices=[('revenue', 'Doanh thu'), ('expense', 'Chi phí'), ('cash_flow', 'Dòng tiền ròng')], max_length=20)),
                ('period_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('period_year', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['period_year', 'period_month'],
                'unique_together': {('forecast_type', 'period_month', 'period_year')},
            },
        ),
    ]
