# Generated by Django 5.2.10 on 2026-01-12 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insight_type', models.CharField(choices=[('resource_performance', 'Resource Performance'), ('project_staffing', 'Project Staffing'), ('sales_improvement', 'Sales Improvement'), ('purchasing_improvement', 'Purchasing Improvement'), ('budget_optimization', 'Budget Optimization'), ('general', 'General')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('insights', models.TextField()),
                ('recommendations', models.TextField()),
                ('context_data', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
