# Generated by Django 5.2.10 on 2026-01-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Toàn thời gian'), ('part_time', 'Bán thời gian'), ('contractor', 'Hợp đồng'), ('intern', 'Thực tập')], default='full_time', max_length=20),
        ),
    ]
