# Generated by Django 5.2.10 on 2026-01-19 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_employee_employment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, help_text='Chức vụ (tự do hoặc chọn từ danh sách)', max_length=100),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Tên chức vụ', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả chức vụ')),
                ('is_active', models.BooleanField(default=True, help_text='Chức vụ còn hoạt động')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chức vụ',
                'verbose_name_plural': 'Chức vụ',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position_fk',
            field=models.ForeignKey(blank=True, help_text='Chức vụ từ danh sách', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='resources.position'),
        ),
    ]
