# Generated by Django 5.2.10 on 2026-01-22 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_employee_position_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_day', models.IntegerField(choices=[(1, 'Ngày 1'), (2, 'Ngày 2'), (3, 'Ngày 3'), (4, 'Ngày 4'), (5, 'Ngày 5'), (6, 'Ngày 6'), (7, 'Ngày 7'), (8, 'Ngày 8'), (9, 'Ngày 9'), (10, 'Ngày 10'), (11, 'Ngày 11'), (12, 'Ngày 12'), (13, 'Ngày 13'), (14, 'Ngày 14'), (15, 'Ngày 15'), (16, 'Ngày 16'), (17, 'Ngày 17'), (18, 'Ngày 18'), (19, 'Ngày 19'), (20, 'Ngày 20'), (21, 'Ngày 21'), (22, 'Ngày 22'), (23, 'Ngày 23'), (24, 'Ngày 24'), (25, 'Ngày 25'), (26, 'Ngày 26'), (27, 'Ngày 27'), (28, 'Ngày 28')], default=5, help_text='Ngày phát lương trong tháng (1-28)')),
                ('notes', models.TextField(blank=True, help_text='Ghi chú về lịch phát lương')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_schedule', to='resources.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch phát lương',
                'verbose_name_plural': 'Lịch phát lương',
                'ordering': ['-created_at'],
            },
        ),
    ]
