# Generated by Django 5.2.10 on 2026-01-22 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_payrollschedule_employee'),
    ]

    operations = [
        # Merge migration - không có operations vì cả hai branches đều làm cùng một việc
        # (remove employee field và add is_active field)
    ]
