# Generated by Django 5.2.10 on 2026-01-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_employeehourlyrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollschedule',
            name='employee',
        ),
        migrations.AddField(
            model_name='payrollschedule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Lịch phát lương đang hoạt động'),
        ),
    ]
