# Generated by Django 5.2.11 on 2026-03-07 12:25

import django.db.models.deletion
from django.db import migrations, models


def populate_department_codes(apps, schema_editor):
    """Gán mã phòng ban cho các bản ghi hiện có."""
    Department = apps.get_model('resources', 'Department')
    for i, dept in enumerate(Department.objects.all(), start=1):
        # Tạo mã từ tên phòng ban (3 ký tự đầu viết hoa) + số thứ tự
        name_prefix = ''.join(c for c in dept.name.upper() if c.isalpha())[:3]
        if not name_prefix:
            name_prefix = 'DEP'
        dept.code = f'{name_prefix}{i:02d}'
        dept.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_remove_payrollschedule_employee_and_more'),
    ]

    operations = [
        # Step 1: Add code field WITHOUT unique constraint
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Mã phòng ban', max_length=20),
        ),
        # Step 2: Add is_active field
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Trạng thái hoạt động'),
        ),
        # Step 3: Add parent field
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Phòng ban cha', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resources.department'),
        ),
        # Step 4: Populate codes for existing departments
        migrations.RunPython(populate_department_codes, migrations.RunPython.noop),
        # Step 5: Now add unique constraint on code
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Mã phòng ban', max_length=20, unique=True),
        ),
    ]
