# Generated by Django 5.2.11 on 2026-04-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_department_code_department_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='at_risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='bonus_reduction_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='delay_penalty_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='kpi_current',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='penalty_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_delay_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='warning_count',
            field=models.IntegerField(default=0),
        ),
    ]
